version: '3.8'

services:
  feria-usm-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feria-usm-app
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - feria-network

networks:
  feria-network:
    driver: bridge
